import LegalLayout, { OPERATOR } from './LegalLayout';
import { useLanguage } from '../../hooks/useLanguage';

// AVISO LEGAL — required by Ley 34/2002 (LSSI-CE) Art. 10 for any provider of
// "information society services" established in Spain. This is the page Spanish
// regulators look for first, and its absence is the most commonly fined
// omission for small Spanish web services.
export default function Notice() {
  const { lang } = useLanguage();
  const isEs = lang === 'es';

  const en = [
    { heading: '1. Identification of the provider', body: [
      'In compliance with the duty of information under Article 10 of Spanish Law 34/2002 of 11 July, on Information Society Services and Electronic Commerce (LSSI-CE), the following details are provided:',
      [
        `Owner: ${OPERATOR.name}`,
        `Tax ID (NIF/NIE): ${OPERATOR.taxId}`,
        `Address: ${OPERATOR.address}`,
        `Email: ${OPERATOR.email}`,
        'Activity: provision of a free online habit-tracking application.',
      ],
    ]},
    { heading: '2. Purpose', body: [
      'This notice governs access to and use of the ASCEND website and application ("the Site"). Browsing the Site confers the status of user and implies full acceptance of this notice, the Terms of Use, the Privacy Policy and the Cookie Policy.',
    ]},
    { heading: '3. Conditions of access', body: [
      'Access to the Site is free of charge. Access to certain functions requires prior registration of a user account.',
      'The user undertakes to use the Site in accordance with the law, this notice, public order and good faith, and to refrain from using it for unlawful purposes or purposes harmful to third parties.',
    ]},
    { heading: '4. Intellectual and industrial property', body: [
      'The source code, graphic design, texts, illustrations, video and audio material, brand elements and any other content of the Site are the property of the owner or are used under licence, and are protected by intellectual and industrial property law.',
      'Reproduction, distribution, public communication or transformation of any element of the Site is prohibited without the express written authorisation of the owner. Use of the trade name and logo "ASCEND" without such authorisation is likewise prohibited.',
      'Content generated by users remains the property of those users, under the terms set out in the Terms of Use.',
    ]},
    { heading: '5. Liability', body: [
      'The owner is not liable for interruptions, errors or failures in access to the Site, nor for damage arising from the presence of viruses or other harmful elements introduced by third parties.',
      'The owner is not liable for the content of external sites accessible via links, nor for their availability or accuracy.',
      'The owner reserves the right to modify, suspend or discontinue the Site or any of its services at any time, without prior notice, and without liability arising for such reason.',
    ]},
    { heading: '6. Personal data protection', body: [
      'The processing of personal data collected through the Site is governed by the Privacy Policy, which forms an integral part of this notice.',
    ]},
    { heading: '7. Applicable law and jurisdiction', body: [
      'This notice is governed by Spanish law.',
      'For the resolution of any dispute arising from access to or use of the Site, the parties submit to the courts of the owner\'s domicile, unless the applicable rules on consumers and users establish a different jurisdiction, in which case the latter prevails.',
    ]},
    { heading: '8. Alternative dispute resolution', body: [
      'In accordance with Regulation (EU) 524/2013, users resident in the European Union may access the online dispute resolution platform of the European Commission at ec.europa.eu/consumers/odr.',
    ]},
  ];

  const es = [
    { heading: '1. Identificación del prestador', body: [
      'En cumplimiento del deber de información recogido en el artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), se facilitan los siguientes datos:',
      [
        `Titular: ${OPERATOR.name}`,
        `NIF/NIE: ${OPERATOR.taxId}`,
        `Domicilio: ${OPERATOR.address}`,
        `Correo electrónico: ${OPERATOR.email}`,
        'Actividad: prestación de una aplicación web gratuita de seguimiento de hábitos.',
      ],
    ]},
    { heading: '2. Objeto', body: [
      'El presente aviso legal regula el acceso y uso del sitio web y la aplicación ASCEND ("el Sitio"). La navegación por el Sitio atribuye la condición de usuario e implica la aceptación plena del presente aviso, de los Términos de uso, de la Política de privacidad y de la Política de cookies.',
    ]},
    { heading: '3. Condiciones de acceso', body: [
      'El acceso al Sitio es gratuito. El acceso a determinadas funcionalidades requiere el registro previo de una cuenta de usuario.',
      'El usuario se compromete a utilizar el Sitio conforme a la ley, al presente aviso, al orden público y a la buena fe, absteniéndose de emplearlo con fines ilícitos o lesivos para terceros.',
    ]},
    { heading: '4. Propiedad intelectual e industrial', body: [
      'El código fuente, el diseño gráfico, los textos, las ilustraciones, el material de vídeo y audio, los elementos de marca y cualesquiera otros contenidos del Sitio son propiedad del titular o se utilizan bajo licencia, y están protegidos por la normativa de propiedad intelectual e industrial.',
      'Queda prohibida la reproducción, distribución, comunicación pública o transformación de cualquier elemento del Sitio sin la autorización expresa y por escrito del titular. Queda igualmente prohibido el uso del nombre comercial y del logotipo "ASCEND" sin dicha autorización.',
      'Los contenidos generados por los usuarios siguen siendo propiedad de estos, en los términos previstos en los Términos de uso.',
    ]},
    { heading: '5. Responsabilidad', body: [
      'El titular no se responsabiliza de las interrupciones, errores o fallos en el acceso al Sitio, ni de los daños derivados de la presencia de virus u otros elementos lesivos introducidos por terceros.',
      'El titular no se responsabiliza del contenido de los sitios externos accesibles mediante enlaces, ni de su disponibilidad o exactitud.',
      'El titular se reserva el derecho a modificar, suspender o discontinuar el Sitio o cualquiera de sus servicios en cualquier momento, sin previo aviso, sin que de ello se derive responsabilidad alguna.',
    ]},
    { heading: '6. Protección de datos personales', body: [
      'El tratamiento de los datos personales recogidos a través del Sitio se rige por la Política de privacidad, que forma parte integrante del presente aviso.',
    ]},
    { heading: '7. Legislación aplicable y jurisdicción', body: [
      'El presente aviso se rige por la legislación española.',
      'Para la resolución de cualquier controversia derivada del acceso o uso del Sitio, las partes se someten a los juzgados y tribunales del domicilio del titular, salvo que la normativa aplicable en materia de consumidores y usuarios establezca un fuero distinto, en cuyo caso prevalecerá este último.',
    ]},
    { heading: '8. Resolución alternativa de litigios', body: [
      'Conforme al Reglamento (UE) 524/2013, los usuarios residentes en la Unión Europea pueden acceder a la plataforma de resolución de litigios en línea de la Comisión Europea en ec.europa.eu/consumers/odr.',
    ]},
  ];

  return (
    <LegalLayout
      title={isEs ? 'Aviso legal' : 'Legal Notice'}
      subtitle={isEs
        ? 'Información del prestador del servicio, conforme al artículo 10 de la LSSI-CE.'
        : 'Service provider information, as required by Article 10 of Spain\'s LSSI-CE.'}
      sections={isEs ? es : en}
    />
  );
}
